import { getEventExportData } from "@/lib/events/actions";
import {
  formatCategory,
  formatEventDate,
  formatEventType,
  formatMoney,
} from "@/lib/format";

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ eventId: string }> },
) {
  const { eventId } = await params;

  let data;
  try {
    data = await getEventExportData(eventId);
  } catch {
    return new Response("Not found", { status: 404 });
  }

  const { event, completedTasks, openTasks, totalSpent, totalIncome, budgetItems } = data;
  const currency = event.currency ?? "USD";

  const lines: string[] = [
    `# ${event.name} — Event Report`,
    "",
    `- **Type:** ${formatEventType(event.type)}`,
    `- **Date:** ${formatEventDate(event.date)}`,
    ...(event.location ? [`- **Location:** ${event.location}`] : []),
    ...(event.audience_size ? [`- **Expected audience:** ${event.audience_size}`] : []),
    `- **Completed tasks:** ${completedTasks.length}`,
    `- **Open tasks:** ${openTasks.length}`,
    `- **Total spent:** ${formatMoney(totalSpent, currency)}`,
    `- **Sponsor income:** ${formatMoney(totalIncome, currency)}`,
    "",
  ];

  if (event.plan_summary) {
    lines.push("## Plan summary", "", event.plan_summary, "");
  }

  if (completedTasks.length) {
    lines.push(`## Completed checklist (${completedTasks.length})`, "");
    for (const task of completedTasks) {
      lines.push(`- [x] **${formatCategory(task.category)}** — ${task.title}`);
    }
    lines.push("");
  }

  if (openTasks.length) {
    lines.push(`## Open tasks (${openTasks.length})`, "");
    for (const task of openTasks) {
      lines.push(`- [ ] **${formatCategory(task.category)}** — ${task.title}`);
    }
    lines.push("");
  }

  const expenses = budgetItems.filter((b) => b.item_type === "expense");
  if (expenses.length) {
    lines.push("## Expense summary", "", "| Item | Category | Estimated | Actual |", "| --- | --- | ---: | ---: |");
    for (const item of expenses) {
      lines.push(
        `| ${item.label} | ${item.category} | ${formatMoney(Number(item.estimated), currency)} | ${formatMoney(Number(item.actual), currency)} |`,
      );
    }
    lines.push("");
  }

  if (event.notes) {
    lines.push("## Notes / lessons learned", "", event.notes, "");
  }

  lines.push("---", "", "Generated by EventPlanner");

  const slug = event.name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60) || "event";

  return new Response(lines.join("\n"), {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Disposition": `attachment; filename="${slug}-report.md"`,
    },
  });
}
